name: Verify code formatting and linting for python connector

permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - '.github/workflows/python-connector-code-check.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - '.github/workflows/python-connector-code-check.yml'
  # Give us a button to allow running the workflow on demand for testing.
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Workflow Run'
        required: false
        type: string

jobs:
  connector-verify-code:
    name: Python connector code verification
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required by aws-actions/configure-aws-credentials
    concurrency:
      # Ensure only 1 job uses the workflow cluster at a time.
      group: ${{ github.workflow }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Configure and install dependencies
      working-directory: ./
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -e ".[dev]"
        pip install poetry
    
    - name: Run mypy - static type checking
      run: |
        source .venv/bin/activate
        poetry run mypy .
    
    - name: Run flake8 - linting
      run: |
        source .venv/bin/activate
        poetry run flake8 .
    
    - name: Run isort - dependency import sorting check
      run: |
        source .venv/bin/activate
        poetry run isort --check-only .

