name: Python connector integration tests

permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - '.github/workflows/python-connector-integration-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - '.github/workflows/python-connector-integration-tests.yml'
  # Give us a button to allow running the workflow on demand for testing.
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Workflow Run'
        required: false
        type: string

jobs:
  connector-integ-test:
    name: Python connector integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      contents: read
      id-token: write # required by aws-actions/configure-aws-credentials
    concurrency:
      # Ensure only 1 job uses the workflow cluster at a time.
      group: ${{ github.workflow }}-${{ matrix.python-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.PYTHON_CONNECTOR_IAM_ROLE }}
        aws-region: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_REGION }}

    - name: Configure and run integration tests - admin
      env:
        CLUSTER_USER: "admin"
        CLUSTER_ENDPOINT: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_ENDPOINT }}
        REGION: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_REGION }}
        SSL_CERT_PATH: "./root.pem"
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -e ".[psycopg,psycopg2,asyncpg,dev]"
        python3 -c "import boto3; print(boto3.__version__)"
        pip list
        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
        wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O root.pem
        python -m pytest tests/integration

    - name: Run psycopg example smoke tests
      working-directory: ./examples/psycopg
      env:
        CLUSTER_USER: "admin"
        CLUSTER_ENDPOINT: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_ENDPOINT }}
        REGION: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_REGION }}
        SSL_CERT_PATH: "./root.pem"
      run: |
        source ../../.venv/bin/activate
        pip install -e ".[test]"
        wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O root.pem
        python -m pytest

    - name: Run psycopg2 example smoke tests
      working-directory: ./examples/psycopg2
      env:
        CLUSTER_USER: "admin"
        CLUSTER_ENDPOINT: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_ENDPOINT }}
        REGION: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_REGION }}
        SSL_CERT_PATH: "./root.pem"
      run: |
        source ../../.venv/bin/activate
        pip install -e ".[test]"
        wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O root.pem
        python -m pytest

    - name: Run asyncpg example smoke tests
      working-directory: ./examples/asyncpg
      env:
        CLUSTER_USER: "admin"
        CLUSTER_ENDPOINT: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_ENDPOINT }}
        REGION: ${{ secrets.AURORA_DSQL_INTEGRATION_CLUSTER_REGION }}
        SSL_CERT_PATH: "./root.pem"
      run: |
        source ../../.venv/bin/activate
        pip install -e ".[test]"
        wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O root.pem
        python -m pytest
